### ISSUE TITLE
Nice job on Smart Animals, Question Please

### ISSUE THREAD

**Issue by oleteacher** [Huniko519/Smart-Animals-ChatGPT3-HTML#2]
Very nice job on smart animals, will be using this in the classroom for some younger children.

Is there a way to also use gpt-3.5-turbo model?

Thank you for sharing smart animals.

**Comment by Huniko519** [comment]
Hi @oleteacher.
Nice to meet u.
Here is avaliable soultion.
<br>
![image](https://user-images.githubusercontent.com/71299022/232351469-349b41bc-78cf-4633-99d2-171b1bc9d0c7.png)
"text-davinci-003" => "gpt-3.5-turbo"
<br>
https://platform.openai.com/docs/models/gpt-3-5
<br>
![image](https://user-images.githubusercontent.com/71299022/232351610-ad6102e7-9b4c-4c92-a798-c11d2bb57d9b.png)

**Comment by oleteacher** [comment]
Very nice to meet you too @Huniko519 . You have a very nice project going:)

I tried to change the $model soon as I found your github:

```
$url = 'https://api.openai.com/v1/completions';
$model = "gpt-3.5-turbo";
```
![image](https://user-images.githubusercontent.com/26278259/232354380-79a461ae-01f6-40de-a59f-21f46c474e5f.png)

Works great with:

```
$url = 'https://api.openai.com/v1/completions';
$model = "text-davinci-003";
```
![image](https://user-images.githubusercontent.com/26278259/232354429-180c0d33-d0e5-4517-868a-523a75924560.png)

Just in case I tried but was pretty sure it would not work:

```
$url = 'https://api.openai.com/v1/completions';
$model = "text-davinci-003" => "gpt-3.5-turbo";
```

**Comment by Huniko519** [comment]
![image](https://user-images.githubusercontent.com/71299022/232356561-9998c396-e5c7-4b69-858d-307c0af5fc59.png)

Please check it.
https://platform.openai.com/docs/guides/fine-tuning/preparing-your-dataset

**Comment by oleteacher** [comment]
Thanks. I am not trying to fine tune; I am trying to use gpt-3.5-turbo model as an option. Fully aware that gpt-3.5-turbo ignores the fine-tuning option.

Only trying gpt-3.5-turbo because it is cheaper:)
